[tool.poetry]
name = "Playwright connect to remote browser"
version = "0.1.0"
description = ""
authors = ["sergerdn <>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
playwright = "^1.32.1"

[tool.poetry.group.dev.dependencies]
pytest = "^6.0.0"
pytest-mock = "*"
vcrpy = "^4.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
